export type ApiErrorCode =
  | "MISSING_SPREADSHEET_ID"
  | "INVALID_SPREADSHEET_ID"
  | "MISSING_SHEET_ID"
  | "INVALID_SHEET_ID"
  | "INVALID_RANGE"
  | "UNAUTHORIZED"
  | "FORBIDDEN"
  | "NOT_FOUND"
  | "RATE_LIMITED"
  | "INTERNAL_ERROR";
